name: Risk Tier

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  risk-tier:
    # Pin to a full commit SHA for supply-chain safety instead of @main
    uses: phishfort/risk-tier-policy-gate/.github/workflows/risk-tier-reusable.yml@main
    secrets: inherit
