name: Risk Tier

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  risk-tier:
    uses: phishfort/risk-tier-policy-gate/.github/workflows/risk-tier-reusable.yml@main
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
